name: socially
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  liquid_pull_to_refresh: ^3.0.1
  logging: ^1.3.0
  photo_view: ^0.15.0
  shared_preferences: ^2.3.1
  smooth_page_indicator: ^1.2.0+3
  story: ^1.1.0
  timeago: ^3.7.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Glory
      fonts:
        - asset: assets/fonts/glory/Glory-Regular.ttf
          weight: 400
        - asset: assets/fonts/glory/Glory-Medium.ttf
          weight: 500
        - asset: assets/fonts/glory/Glory-Bold.ttf
          weight: 700
